method: random
metric:
  name: mean_val_loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.0001] # , .003] #, 0.003, 0.001, 0.01]
  batch_size:
    values: [2048] #64, 128, 256]
  regularization:
    values: ['l1'] #, 'l1', 'l2'
  lambda_reg:
    values: [0.01] #, 0.1, 1.0] #0.1, 0.5, 1.0, 2.0]
  input_dim:
    value: !!int 0 
  epochs:
    values: [200] # , 100, 200] #, 200]