method: random
metric:
  name: mean_val_loss
  goal: minimize
parameters:
  activation:
    values: ['none'] # 'none','relu', 'sigmoid', 'softplus']
  learning_rate:
    values: [0.003, 0.001, 0.01]
  batch_size:
    values: [128, 256, 512]
  regularization:
    values: ['l1', 'l2']
  lambda_reg:
    values: [0.01, 0.1, 1.0, 10.0]
  shared_weights:
    values: [True, False]
  input_dim:
    value: !!int 0 
  reduced_dim:
    values: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  epochs:
    values: [100, 150]
  # early_terminate:
  #   type: hyperband
  #   s: 2
  #   eta: 3
  #   max_iter: 10

# hand tuned parameters:
#   activation:
#     values: ['none'] 
#   learning_rate:
#     values: [0.001]
#   batch_size:
#     values: [128] 
#   regularization:
#     values: ['l2']
#   lambda_reg:
#     values: [0.1] 
#   shared_weights:
#     values: [False] 
#   input_dim:
#     value: !!int 0 
#   reduced_dim:
#     values: [5] 
#   epochs:
#     values: [100] 
