method: random
metric:
  name: mean_val_loss
  goal: minimize
# parameters:
#   learning_rate:
#     values: [0.01, 0.005, 0.001]
#   batch_size:
#     values: [512, 1024, 2048]
#   regularization:
#     values: ['l1', 'l2']
#   lambda_reg:
#     values: [0.01, 0.1, 1.0, 100]
#   input_dim:
#     value: !!int 0 
#   epochs:
#     values: [100, 200]

parameters:  # (mainly for no subcortical and PCs)
  learning_rate:
      values: [0.01]
    batch_size:
      values: [1024]
    regularization:
      values: ['l2']
    lambda_reg:
      values: [0.1]
    input_dim:
      value: !!int 0 
    epochs:
      values: [300] 