name: bilinear_SCM
method: random
metric:
  name: mean_val_loss
  goal: minimize

parameters:
  input_dim:
    value: !!int 0
  binarize:
    value: !!int 0
  learning_rate:
    values: [0.00009, 0.0005, 0.001, 0.002]
  batch_size:
    values: [256, 400, 512]
  regularization:
    values: ['l2'] # l2 in line with literature
  lambda_reg:
    values: [0, 0.001, 0.01, 0.1]
  epochs:
    values: [100, 150, 200]

best_parameters:
  input_dim:
    value: !!int 0 
  binarize:
    value: !!int 0
  learning_rate:
    values: [0.002]
  batch_size:
    values: [324]
  regularization:
    values: ['l2']
  lambda_reg:
    values: [0.1]
  epochs:
    values: [300]