name: pls_lineardecoder
method: random
metric:
  name: mean_val_loss
  goal: minimize

# SMALL GRID 
parameters:
  input_dim: 
    value: !!int 0
  binarize: 
    value: !!int 0
  n_components:
    values: [5, 8, 10, 12, 15, 20]
  max_iter:
    values: [1000]
  scale:
    values: [True]
  optimize_encoder:
    values: [False]
  learning_rate:
    values: [0.0035, 0.003, 0.0025]
  batch_size:
    values: [512]
  weight_decay:
    values: [0, 0.01, 0.001, 0.00001]
  epochs:
    values: [75, 100, 150]

best_parameters:
  input_dim: 
    value: !!int 0
  binarize: 
    value: !!int 0
  n_components:
    values: [10]
  max_iter:
    values: [1000]
  scale:
    values: [True]
  optimize_encoder:
    values: [False]
  learning_rate:
    values: [0.0035]
  batch_size:
    values: [512]
  weight_decay:
    values: [0.01]
  epochs:
    values: [75]