name: pls
method: random
metric:
  name: mean_val_loss
  goal: minimize

# SMALL GRID 
parameters:
  input_dim: 
    value: !!int 0
  binarize: 
    value: !!int 0
  encoder_indices:
    value: !!int 0
  n_components:
    values: [2, 3, 5, 7, 10, 15, 20, 30]
  max_iter:
    values: [1000]
  scale:
    values: [True, False]
  hidden_dims:
    values:     
    - [128, 64]
    - [256, 128]
  learning_rate:
    values: [0.0001, 0.00009]
  batch_size:
    values: [256, 512]
  dropout_rate:
    values: [0.1, 0.2, 0.3]
  weight_decay:
    values: [0.0, 0.0001, 0.001]
  epochs:
    values: [100, 150]

best_parameters:
  input_dim: 
    value: !!int 0
  binarize: 
    value: !!int 0
  encoder_indices:
    value: !!int 0
  n_components:
    values: [10]
  max_iter:
    values: [1000]
  scale:
    values: [True]
  optimize_encoder:
    values: [True]
  hidden_dims:
    values:     
    - [128, 64]
  learning_rate:
    values: [0.0001]
  batch_size:
    values: [512]
  dropout_rate:
    values: [0.2]
  weight_decay:
    values: [0.0001]
  epochs:
    values: [100]
