name: pls_decoder
method: random
metric:
  name: mean_val_loss
  goal: minimize

# SMALL GRID 
parameters:
  input_dim: 
    value: !!int 0
  binarize: 
    value: !!int 0
  decoder:
    values: ['linear', 'bilinear', 'mlp']
  n_components:
    values: [2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 30, 40]
  max_iter:
    values: [1000]
  scale:
    values: [True]
  optimize_encoder:
    values: [False]
  hidden_dims:
    values: 
    - [256, 128]
    - [128, 64]
  learning_rate:
    values: [0.0001, 0.00009, 0.00001]
  batch_size:
    values: [256, 512]
  dropout_rate:
    values: [0.0, 0.2]
  weight_decay:
    values: [0.0, 0.001, 0.0001, 0.00001]
  epochs:
    values: [50, 100, 150]

best_parameters:
  input_dim: 
    value: !!int 0
  binarize: 
    value: !!int 0
  decoder:
    values: ['mlp']
  n_components:
    values: [10]
  max_iter:
    values: [1000]
  scale:
    values: [True]
  optimize_encoder:
    values: [False]
  hidden_dims:
    values:     
    - [128, 64]
  learning_rate:
    values: [0.00009]
  batch_size:
    values: [2048]
  dropout_rate:
    values: [0.2]
  weight_decay:
    values: [0.0001]
  epochs:
    values: [100]