# simple_cnn_sweep.yaml

method: random
metric:
  name: mean_val_loss
  goal: minimize


parameters:
  input_dim:
    value: !!int 0 
  binarize:
    value: false  # FC/SC  false
  learning_rate:
    values: [0.0001, 0.001]
  dropout_rate:
    values: [0.0, 0.1, 0.3]
  weight_decay:
    values: [0.001, 0.005] 

  conv_out_channels:
    values: [32, 64, 128]
  conv_kernel_size:
    values: [7, 15, 31, 51] 

  # pooling layer
  pool_kernel_size:
    values: [4, 8, 16] 

  fc_hidden:
    values: [128, 256]
  optimizer_type:
    value: 'sgd' 
  batch_size:
    value: 256
  epochs:
    value: 30