wandb_version: 1

batch_size:
  value: 40
dropout_rate:
  value: 0.4359055367275973
epochs:
  value: 100
hidden_dims:
  value:
  - 256
  - 128
  - 64
learning_rate:
  value: 0.0001436834706348164
weight_decay:
  value: 0.0001778257033792757
