# Sample experiment config

# Inputs and targets
feature_type:
  - transcriptome: null
train_shared_regions: false
test_shared_regions: false
omit_subcortical: false
dataset: 'UKBB'
parcellation: 'S456'
hemisphere: 'both'
connectome_target: 'FC'

# Gene expression
impute_strategy: 'mirror_interpolate'
sort_genes: 'geneformer_srs'
gene_list: '0.2'
null_model: 'none'

# Cross-validation
cv_type: spatial
resolution: 1.0
random_seed: 42
search_method: ['wandb', 'mse', 5]
track_wandb: true
skip_cv: false
use_folds: [0, 1, 2, 3]

# Model
model_type: shared_transformer
use_gpu: true