# Sample experiment config

# Inputs and targets
feature_type:
  - transcriptome: null
train_shared_regions: false
test_shared_regions: true
omit_subcortical: false
dataset: 'HCP'
parcellation: 'S456'
hemisphere: 'both'
connectome_target: 'FC'
binarize: false

# Gene expression
impute_strategy: 'mirror_interpolate'
sort_genes: 'refgenome'
gene_list: '0.2'
null_model: 'spin'

# Cross-validation
cv_type: schaefer
resolution: 1.0
random_seed: 42
search_method: ['wandb', 'mse', 5]
track_wandb: true
skip_cv: false
use_folds: [0, 1, 2, 3, 4, 5, 6, 7, 8]

# Model
model_type: shared_transformer
use_gpu: true