wandb_version: 1

batch_size:
  value: 48
dropout_rate:
  value: 0.3879110811920825
epochs:
  value: 100
hidden_dims:
  value:
  - 128
  - 64
learning_rate:
  value: 0.008534997549589883
weight_decay:
  value: 1.4923303829349008e-05
