method: random
metric:
  name: mean_val_loss
  goal: minimize
parameters:
  hidden_dims:
    values:
      - [256, 128, 64]
      # - [256, 128]
      # - [512, 256, 128]
  learning_rate:
    values: [0.0001]  #, 0.0003, 0.001, 0.003] # [0.0001, 0.001, 0.003, 0.01, 0.03]
  batch_size:
    values: [128] #, 64] # 16, 32 128
  dropout_rate:
    values: [0] #, 0.1, 0.2] # , 0.1, 0.2, 0.5]
  weight_decay:
    values: [0.0] # 0.001, 0.01] # [0.00001, 0.0001, 0.001, 0.01, 0.0] 
  input_dim:
    value: !!int 0  # Placeholder, replace with actual input_dim in code
  symmetry_weight:
    values: [0.0] #, 0.1, 0.2] # [0.0, 0.01, 0.1, 0.2]
  epochs:
    values: [100] # 300